import { Component, inject, OnInit, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApiService } from '../../../core/services/api.service';
import { Emotion } from '../../../shared/models/models';

@Component({selector:'app-admin-emotions',standalone:true,imports:[ReactiveFormsModule],template:`
<header class="page-head"><div><span class="eyebrow">ADMINISTRACIÓN</span><h1>Catálogo de emociones</h1><p>Gestiona opciones consistentes sin eliminar información histórica.</p></div></header><section class="admin-grid"><form class="panel" [formGroup]="form" (ngSubmit)="create()"><span class="eyebrow">NUEVA EMOCIÓN</span><h2>Agregar al catálogo</h2><label>Nombre<input formControlName="name" placeholder="Ej. Esperanza"></label><button class="btn primary full" [disabled]="form.invalid">Agregar emoción</button></form><article class="panel span-2"><div class="panel-head"><div><span class="eyebrow">CATÁLOGO COMPLETO</span><h2>{{items().length}} emociones</h2></div></div><div class="data-list">@for(e of items();track e.id){<div><span class="status-dot" [class.off]="!e.active"></span><b>{{e.name}}</b><span>{{e.active?'Activa':'Inactiva'}}</span><button class="switch" [class.on]="e.active" (click)="toggle(e)" [attr.aria-label]="'Cambiar estado de '+e.name"><i></i></button></div>}</div></article></section>@if(error()){<div class="alert error">{{error()}}</div>}
`})
export class AdminEmotionsComponent implements OnInit{private readonly fb=inject(FormBuilder);readonly items=signal<Emotion[]>([]);readonly error=signal('');readonly form=this.fb.nonNullable.group({name:['',[Validators.required,Validators.maxLength(80)]]});constructor(private readonly api:ApiService){}ngOnInit():void{this.load();}load():void{this.api.emotions(false).subscribe({next:x=>this.items.set(x),error:()=>this.error.set('No se pudo cargar el catálogo.')});}create():void{if(this.form.invalid)return;this.api.createEmotion(this.form.getRawValue()).subscribe({next:()=>{this.form.reset();this.load();},error:e=>this.error.set(e.status===409?'La emoción ya existe.':'No se pudo crear.')});}toggle(e:Emotion):void{this.api.updateEmotion(e.id,{active:!e.active}).subscribe({next:()=>this.load(),error:()=>this.error.set('No se pudo cambiar el estado.')});}}
