import { Component, inject, OnInit, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApiService } from '../../../core/services/api.service';
import { MicroActivity } from '../../../shared/models/models';

@Component({selector:'app-admin-activities',standalone:true,imports:[ReactiveFormsModule],template:`
<header class="page-head"><div><span class="eyebrow">ADMINISTRACIÓN</span><h1>Microactividades</h1><p>Mantén un catálogo breve, claro y seguro.</p></div></header><section class="admin-grid"><form class="panel" [formGroup]="form" (ngSubmit)="create()"><span class="eyebrow">NUEVA ACTIVIDAD</span><h2>Crear microactividad</h2><label>Título<input formControlName="title"></label><label>Descripción<textarea rows="4" formControlName="description"></textarea></label><label>Duración en minutos<input type="number" min="1" max="60" formControlName="durationMinutes"></label><button class="btn primary full" [disabled]="form.invalid">Crear actividad</button></form><article class="panel span-2"><span class="eyebrow">CATÁLOGO</span><h2>Actividades disponibles</h2><div class="activity-list">@for(a of items();track a.id){<article class="activity-row"><span class="activity-time">{{a.durationMinutes}}<small>min</small></span><div><h3>{{a.title}}</h3><p>{{a.description}}</p></div><button class="switch" [class.on]="a.active" (click)="toggle(a)"><i></i></button></article>}</div></article></section>@if(error()){<div class="alert error">{{error()}}</div>}
`})
export class AdminActivitiesComponent implements OnInit{private readonly fb=inject(FormBuilder);readonly items=signal<MicroActivity[]>([]);readonly error=signal('');readonly form=this.fb.nonNullable.group({title:['',Validators.required],description:['',Validators.required],durationMinutes:[5,[Validators.required,Validators.min(1),Validators.max(60)]]});constructor(private readonly api:ApiService){}ngOnInit():void{this.load();}load():void{this.api.activities(false).subscribe({next:x=>this.items.set(x),error:()=>this.error.set('No se pudo cargar el catálogo.')});}create():void{if(this.form.invalid)return;this.api.createActivity({...this.form.getRawValue(),active:true}).subscribe({next:()=>{this.form.reset({title:'',description:'',durationMinutes:5});this.load();},error:()=>this.error.set('No se pudo crear la actividad.')});}toggle(a:MicroActivity):void{this.api.updateActivity(a.id,{active:!a.active}).subscribe({next:()=>this.load(),error:()=>this.error.set('No se pudo cambiar el estado.')});}}
