app.admin.bootstrap-enabled=${ADMIN_BOOTSTRAP_ENABLED:false}
app.admin.name=${ADMIN_NAME:}
app.admin.email=${ADMIN_EMAIL:}
app.admin.password=${ADMIN_PASSWORD:}
app.admin.birth-date=${ADMIN_BIRTH_DATE:}
app.admin.university=${ADMIN_UNIVERSITY:}
app.admin.career=${ADMIN_CAREER:}
