app.admin.bootstrap-enabled=true
app.admin.name=Administrador Mentaiko
app.admin.email=administrador@mentaiko.com
app.admin.password=Mentaiko123454$
app.admin.birth-date=1990-01-01
app.admin.university=Mentaiko
app.admin.career=Administracion
